// Generated by gencpp from file malpac/test.msg
// DO NOT EDIT!


#ifndef MALPAC_MESSAGE_TEST_H
#define MALPAC_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace malpac
{
template <class ContainerAllocator>
struct test_
{
  typedef test_<ContainerAllocator> Type;

  test_()
    : x(0)  {
    }
  test_(const ContainerAllocator& _alloc)
    : x(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;




  typedef boost::shared_ptr< ::malpac::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::malpac::test_<ContainerAllocator> const> ConstPtr;

}; // struct test_

typedef ::malpac::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::malpac::test > testPtr;
typedef boost::shared_ptr< ::malpac::test const> testConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::malpac::test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::malpac::test_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace malpac

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'malpac': ['/home/dominic/malpac/catkin_ws/src/malpac/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::malpac::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::malpac::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::malpac::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::malpac::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::malpac::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::malpac::test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::malpac::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19aac5e823802d733295ea3ec20e6350";
  }

  static const char* value(const ::malpac::test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19aac5e823802d73ULL;
  static const uint64_t static_value2 = 0x3295ea3ec20e6350ULL;
};

template<class ContainerAllocator>
struct DataType< ::malpac::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "malpac/test";
  }

  static const char* value(const ::malpac::test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::malpac::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
";
  }

  static const char* value(const ::malpac::test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::malpac::test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::malpac::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::malpac::test_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MALPAC_MESSAGE_TEST_H
